"""Generate C# data classes (Unity editor) from a Railroader Definitions.json + each prefab's MaterialMap/AnimationMap.

One class per RR object (loco, tender, ...), all with the same shape, so the builder can treat them alike.

usage: gen_defs.py <Definitions.json> <Assets dir> <out .cs> <ClassName>=<object identifier>=<prefab path> [...]
  e.g. gen_defs.py Definitions.json Assets RgbDefs.cs RgbDefs=rlw_0-10-0-bertha=Assets/prefabs/.../rlw-0-10-0-bertha.prefab
"""
import json, os, re, sys, glob

defs_path, assets, out = sys.argv[1:4]
targets = [a.split('=', 2) for a in sys.argv[4:]]
objects = {o['identifier']: o['definition'] for o in json.load(open(defs_path, encoding='utf-8'))['objects']}

guid_path = {}
for meta in glob.glob(os.path.join(assets, '**', '*.meta'), recursive=True):
    g = re.search(r'guid: (\w+)', open(meta, encoding='utf-8').read())
    if g:
        guid_path[g.group(1)] = 'Assets/' + os.path.relpath(meta[:-5], assets).replace('\\', '/')


def s(x):
    return '"' + str(x).replace('\\', '\\\\').replace('"', '\\"') + '"'


def f(x):
    return repr(float(x)) + 'f'


def v3(a):
    return 'new Vector3(%s, %s, %s)' % tuple(f(x) for x in a)


def q(a):
    return 'new Quaternion(%s, %s, %s, %s)' % tuple(f(x) for x in a)


EXTRA_KEYS = ('style', 'prefab', 'content', 'defaultText', 'forceColor', 'size', 'height', 'radius', 'slotIndex', 'forward',
              'purpose', 'rotationDegrees', 'momentary', 'homePosition', 'collider', 'forwardOffset', 'keyframes', 'key', 'animation',
              'targetColliderObject', 'activateComponents', 'material', 'materialName', 'matchNameExact', 'colorID', 'model', 'cylinderType', 'secondWheelsetStartingOffset',
              'secondWheelsetIndex', 'truckId', 'end', 'direction', 'truckOffset', 'priority', 'lightEnabled', 'speed', 'messageTrue',
              'messageFalse', 'title', 'loadIdentifier')

L = ['// GENERATED by tools/gen_defs.py from the RR Definitions.json and prefab maps. Do not edit.',
     'using System.Collections.Generic;\nusing UnityEngine;\n']
for cls, ident, prefab_path in targets:
    d = objects[ident]
    prefab_file = os.path.join(assets, os.path.relpath(prefab_path, 'Assets'))
    txt = open(prefab_file, encoding='utf-8').read()
    matmap = re.findall(r'- name: (.+)\n\s+material: \{fileID: \d+, guid: (\w+)', txt)
    animmap = re.findall(r'- name: (.+)\n\s+clip: \{fileID: \d+, guid: (\w+)', txt)
    slots = {sl['requiredLoadIdentifier']: sl['maximumCapacity'] for sl in d.get('loadSlots', [])}

    L.append('// RR object %s (%s), model %s' % (ident, d.get('kind'), d.get('modelIdentifier')))
    L.append('public static class %s\n{' % cls)
    L.append('    public struct Comp { public string kind, name, parentPath, extra; public Vector3 pos, scale; public Quaternion rot; }')
    L.append('    public const string Identifier = %s, Kind = %s, Prefab = %s;' % (s(ident), s(d.get('kind')), s(prefab_path)))
    L.append('    public const float PositionHead = %s, PositionTail = %s, Length = %s, CouplerHeight = %s, WeightEmptyLb = %s;' % (
        f(d.get('positionHead', d.get('length', 0) / 2)), f(d.get('positionTail', -d.get('length', 0) / 2)), f(d.get('length', 0)),
        f(d.get('couplerHeight', 0)), f(d.get('weightEmpty', 0))))
    L.append('    public const float CoalCapacityLb = %s, WaterCapacityGal = %s, MaxBoilerPsi = %s, TruckSeparation = %s;' % (
        f(slots.get('coal', 0)), f(slots.get('water', 0)), f(d.get('maximumBoilerPressure', 0)), f(d.get('truckSeparation', 0))))
    L.append('    public const float PistonDiameterIn = %s, PistonStrokeIn = %s, HeatingSurfaceSqFt = %s, WeightOnDriversLb = %s, PublishedTractiveEffortLb = %s;' % (
        f(d.get('pistonDiameterInches', 0)), f(d.get('pistonStrokeInches', 0)), f(d.get('totalHeatingSurface', 0)),
        f(d.get('weightOnDrivers', 0)), f(d.get('publishedTractiveEffort', 0))))
    L.append('    public const string TenderIdentifier = %s, TruckIdentifier = %s;' % (s(d.get('tenderIdentifier', '')), s(d.get('truckIdentifier', ''))))
    L.append('    public static readonly Vector3 AirHose = %s;' % v3(d.get('airHosePosition', [0, 0, 0])))
    L.append('    public static readonly (float offset, float length, float diameter, int axles, string clip)[] Wheelsets = {')
    for w in d.get('wheelsets', []):
        L.append('        (%s, %s, %s, %d, %s),' % (f(w['offset']), f(w['length']), f(w['diameter']), w['numberOfAxles'], s(w['animation']['clipName'])))
    L.append('    };')
    L.append('    public static readonly Dictionary<string, string> MaterialMap = new Dictionary<string, string> {')
    for n, g in matmap:
        L.append('        { %s, %s },' % (s(n.strip()), s(guid_path.get(g, g))))
    L.append('    };')
    L.append('    public static readonly Dictionary<string, string> AnimationMap = new Dictionary<string, string> {')
    for n, g in animmap:
        L.append('        { %s, %s },' % (s(n.strip()), s(guid_path.get(g, g))))
    L.append('    };')
    liveries, comps = [], []
    for c in d.get('components', []):
        k = c['kind']
        if k == 'DefaultLivelryComponent':
            liveries.append((c['name'], [(e['id'], e['value']) for e in c['idColors']]))
            continue
        t = c['transform']
        parent = '/'.join(c['parent']['path']) if c.get('parent') else ''
        extra = {key: c[key] for key in EXTRA_KEYS if key in c}
        comps.append((k, c['name'], parent, t['position'], t['rotation'], t['scale'], json.dumps(extra, separators=(',', ':'))))
    L.append('    public static readonly (string name, (string id, string hex)[] colors)[] Liveries = {')
    for n, cols in liveries:
        L.append('        (%s, new[] { %s }),' % (s(n), ', '.join('(%s, %s)' % (s(i), s(h)) for i, h in cols)))
    L.append('    };')
    L.append('    public static readonly Comp[] Components = {')
    for k, n, p, pos, rot, sc, ex in comps:
        L.append('        new Comp { kind = %s, name = %s, parentPath = %s, pos = %s, rot = %s, scale = %s, extra = %s },' % (
            s(k), s(n), s(p), v3(pos), q(rot), v3(sc), s(ex)))
    L.append('    };')
    L.append('}\n')
    print(cls, ident, len(comps), 'components', len(liveries), 'liveries', len(matmap), 'material map', len(animmap), 'anim map')
open(out, 'w', encoding='utf-8').write('\n'.join(L) + '\n')
print('wrote', out)
